### ISSUE TITLE
[DATA] LIBRE - Sentiment Analysis

### ISSUE THREAD

**Issue by vladnn100** [unmsmfisi-socialapplication/social_app#112]
**Sentiment Analysis with PyTorch**

- In this activity, I propose to implement a sentiment analysis powered by pytorh using LSTM.
- The dataset to be used for this task is "IMDB Dataset of 50K Movie Reviews", which originated from a IMDB Dataset project (https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews).

### 1. Task Objective
- The objective of this task is to train and evaluate the model called LSTM using previously processed data.

### 2. Task Requirement

| Requirement | Name | Definition |
| --- | --- | --- |
| R_P01 | Code commenting | Include comments in the source code to explain its functionality and make it easier to understand. |
| R_M02 | Model parameter selection | Select the appropriate parameters to set up the LSTM model. |
| R_M03 | Model evaluation | Perform performance tests on models using metrics such as accuracy, F1 score, and ROC curves. |

### 3. Model chosen and parameterization.

**Sentiment RNN**
[https://docs.google.com/document/d/19_wzXbPOXveppNAtzWEGVTD6BVrhcaFDzSUG3WSNfzI/edit?usp=sharing](url)

### 4. Pull request and commit
- All the files necessary for the implementation, such as the python code with the different models applying "PyTorch" and the data used, will be integrated into the repository by "Pull Request" through the "**DATA_add_as_pytorch**" branch.

### 5. Results
Pendient

### 6. Discussion
Pendient

**Comment by ZDev-19** [comment]
This issue is being closed due to official Sentiment analysis model selected from @syntx8 .
