### ISSUE TITLE
[DATA] Model for spam detection (3)

### ISSUE THREAD

**Issue by Patrickpisana23** [unmsmfisi-socialapplication/social_app#117]
**Objective of the task**

This problem must add models for spam detection in comments, using the naive bayes model. In addition, the model must be tested and parameterized according to the context of the project.

**Comment by Patrickpisana23** [comment]
| Requirement| Name | Definition |
|--------|--------|--------|
| R_P01| Comment code| The jupyter must be commented on in each script|
| R_M02| Select model parameters| Models must be with parameters according to the context|
| R_M03| Model testing| Models must be tested for performance such as confusion matrix, f1score|

**Comment by beltocas** [comment]
Task completed, where the pull request was approved, based on the meeting of 09/28
