### ISSUE TITLE
[DATA] Weekly Meeting (08/09/23)

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#146]
### **Objective**

Accord data conventions in pull requests , issues structure , new file structure and branches.

**Comment by ZDev-19** [comment]
### **Data branches update**

According to meeting held at discord with DATA Team assignees , past DATA branches will be deleted and three new ones are going to be created: 

- DATA_add_sa: Branch contains commits about Sentiment analysis
- DATA_add_pc : Branch contains commits about Post classification
- DATA_add_sp : Branch contains commits about Spam detection

New project structure are set in the following issue: https://github.com/orgs/unmsmfisi-socialapplication/projects/1/views/1?filterQuery=DATA&pane=issue&itemId=38114617

**Comment by ZDev-19** [comment]
### **Pull requests update**

Pull requests are deleted due to new conventions , is accorded that for the following features are going to exist eleven(11) pull requests , each one for every data team member

**Comment by ZDev-19** [comment]
### **Branches last update**

Conventions are modified due to errors in PR , convetions stay but are modified in the following structure:

- DATA_feature_name_process_name

**Comment by beltocas** [comment]
Close by Meeting 28/09
