### ISSUE TITLE
[DATA] Comment sentiment analysis pre-processing

### ISSUE THREAD

**Issue by Edward-Htc** [unmsmfisi-socialapplication/social_app#147]
**1. Objective of the issue/task:**

It is intended to extract information from Twitter through the twint API, this API allows us to extract the comments of a specific topic, period and language. Subsequently, the pre-processing of the natural language will be carried out, finding the regular expressions such as special characters or the alphabet. Subsequently, the lemmatization of each comment will be made to be able to leave it ready for modeling.

**2. Task requirements:**
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-568f7e42-7fff-ae62-0877-f729c5dd1fb2"><div dir="ltr" style="margin-left:0pt;" align="center">

Requirements| Name| Definition
-- | -- | --
R_P01 | Comment code | The elaborated code must be commented for its better understanding
R_P02 | Extraction of information | The comments will be extracted with the twint API
R_P03 | Data set cleanup | Finding regular expressions and lemmatization

</div></b>
</body>
</html>

**3. Origin of the data set**

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-87281d3c-7fff-6616-aea7-97416bf3af22"><div dir="ltr" style="margin-left:0pt;" align="right">

ID | Name | Description
-- | -- | --
D01 | Twint | API that performs web scraping twitter comments on a specific or general topic, with a specific language and period.

</div></b>
</body>
</html>

**4. Data Dictionary**

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-f7ca09b6-7fff-0df4-ada9-ac09161db97e"><div dir="ltr" style="margin-left:0pt;" align="right">

ID | Variable | Descripción
-- | -- | --
D01 | date | Publication date
D02 | username | Name of the user who tweeted
D03 | language | tweet language
D04 | tweet | Tweet
D05 | nlikes | number of likes

</div></b>
</body>
</html>

**5. Final structure**

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-f1d5ec3e-7fff-3778-ffa6-3185a40a355a"><div dir="ltr" style="margin-left:72pt;" align="left">

ID | Name | Type | Description
-- | -- | -- | --
V-01 | Comentario | object | Comment classification (negative or positive)
V-02 | Score | int64 | Score that helps to classify the V-01 dice
V-03 | Tweet | object. | Full tweet preprocessed
V-04 | Lista | object | Classification according to technology topic

</div></b>
</body>
</html>

**Comment by ZDev-19** [comment]
Closed due to member quitting the DATA team
