### ISSUE TITLE
[FE] : feature (Component) :  input Login

### ISSUE THREAD

**Issue by AnthonyRicse98** [unmsmfisi-socialapplication/social_app#163]
crear un componente input usando material iu , este componente debe tener como minimo props text , para colocar icon , mantener los colores de la imagenes y el estilo 
El componente es un atomo
Figma : https://www.figma.com/file/WyhCIiSidyM6aXsbxdu1rI/Dise%C3%B1o-UX%2FUI--App-Social?type=design&node-id=6-2&mode=design&t=MN0PkEFiB7bBYLYp-0

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/73305764/ae8b36f4-1d20-4aa2-85ed-00f36bb41322)

EL input ocupa todo el ancho del card

- Usar BEM para el scss 
- Usar las variables del a paleta de colores si es necesario
- Crear un tsx en la carpeta atom recordar que se esta usando el atomic desing
- Seguir las recomendaciones del Readme
- Todas las pruebas colocarlos en la pagina localhost:3000/test

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/73305764/8461ae6d-64c4-460e-8872-1dafb259c79c)

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/73305764/5c8722ef-0698-48fe-a4a3-3d72a946f296)

**Comment by eds000n** [comment]
this is done already, I think we can close this issue
