### ISSUE TITLE
[DEVOPS] Data: Use Google Drive for storing and retrive datasets and models

### ISSUE THREAD

**Issue by aronlabr** [unmsmfisi-socialapplication/social_app#181]
Data'team require a dedicated repository for both training datasets and saving the serialized models intended for production usage.

Google Drive offers several advantages for this purpose. It provides a generous 15GB of complimentary storage space, without any data transfer limitations. Additionally, it simplifies data sharing through the convenient gdown pip package.

```python

pip install --upgrade gdown

import gdown
id = "FILE_ID"
output = "dataset.xlsx" # or skip to use the file's name
gdown.download(id=id, output=output, quiet = True)
```

**Comment by labrdev** [comment]
One potential challenge we might encounter is ensuring the security of our files to prevent unauthorized access. A possibly solution involves employing obfuscation techniques. Specifically, we can achieve this by securely storing the file's identification within a `.env` or `JSON` file, which will be kept internally and shared or stored within a restricted-access Google Drive folder.

```env
DATASET_1_ID = "FILE_ID"
```
```python
from decouple import config
# Read values from .env file
database_url = config('DATASET_1_ID')
```

For JSON:
```json
{
    "DATASET_1_ID" = "FILE_ID"
}
```
```python
import json

# Open and read the JSON file
with open('config.json', 'r') as json_file:
    data = json.load(json_file)
```

The cons is that this add a layer of management complexity to the process.

**Comment by beltocas** [comment]
I agree with using JSON files as a part of the solution to ensure the security of our files and prevent unauthorized access. However, I have some reservations about using Google Drive for internal storage and distribution of these files, as it could add an extra layer of complexity to the project.


Instead, I propose considering the use of a test database with PostgreSQL (progest SQL), as we had discussed from the beginning of the project. This will allow us to have a direct connection to the temporary data we need and simplify the process. Furthermore, a database can provide better access control and security compared to Google Drive. What are your thoughts on this alternative?

example of conection
`conexion = psycopg2.connect("dbname=empleados user=neoguias password=pimientos44")`
