### ISSUE TITLE
[BE] Database structure

### ISSUE THREAD

**Issue by francosilva25** [unmsmfisi-socialapplication/social_app#185]
This issue focuses on the creation of the fundamental tables in the social_app project database. These tables are essential for storing key data related to users, profiles, friends, interests, posts and activities in the application.

The main objectives of this issue are:

1. Table Design: Define the structure of tables, including the fields, data types and constraints needed to store information efficiently and accurately.

2. Table Relationships: Establish appropriate relationships between tables to ensure referential integrity and facilitate future queries and operations.

3. Index Implementation: Identify and create indexes that improve the performance of frequent queries.

**Comment by francosilva25** [comment]
This database includes tables for user accounts, profiles, friendships, posts, comments, reactions and interests. It is designed to store data related to user interactions and content shared within the social network, making it a comprehensive database for managing various aspects of a social networking platform.

# Tables description

<table>
  <thead>
    <tr>
      <th>Tabla</th>
      <th>Descripción</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>SOC_APP_USERS</td>
      <td>This table will store the accounts registered in the platform.</td>
    </tr>
    <tr>
      <td>SOC_APP_USER_PROFILE</td>
      <td>This table will store the profile information of the registered accounts.</td>
    </tr>
    <tr>
      <td>SOC_APP_FRIENDS</td>
      <td>This table will store the friends of the registered accounts.</td>
    </tr>
    <tr>
      <td>SOC_APP_M_USERS_INTERESTS</td>
      <td>This table will be a master that will contain all the interests that will be held within the social network.</td>
    </tr>
    <tr>
      <td>SOC_APP_POSTS</td>
      <td>All posts made by users will be stored in this table.</td>
    </tr>
    <tr>
      <td>SOC_APP_POSTS_COMMENTS</td>
      <td>All comments related to a post will be stored in this table.</td>
    </tr>
    <tr>
      <td>SOC_APP_POSTS_REACTIONS</td>
      <td>In this table all the reactions related to a post will be stored.</td>
    </tr>
    <tr>
      <td>SOC_APP_POSTS_COMMENTS_REACTIONS</td>
      <td>All reactions related to a comment will be stored in this table.</td>
    </tr>
    <tr>
      <td>SOC_APP_USERS_INTERESTS_POSTS</td>
      <td>This table will store the interests associated with a publication.</td>
    </tr>
    <tr>
      <td>SOC_APP_M_USERS_REACTIONS</td>
      <td>This table will be a master that will contain all the types of reactions that will be available on the social network.</td>
    </tr>
  </tbody>
</table>

# ERD Database



![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67833630/6007808f-b091-468c-a12b-5f15ba86bcd2)

**Comment by eds000n** [comment]
this is not how we usually work with databases. Please read this https://www.bytebase.com/blog/what-is-database-schema/ and use one of these tools: https://github.com/go-gorm/gorm/ or https://github.com/golang-migrate/migrate

**Comment by francosilva25** [comment]
Resolved in another PR
