### ISSUE TITLE
[DATA] spam detection

### ISSUE THREAD

**Issue by beltocas** [unmsmfisi-socialapplication/social_app#20]
process posts to check if it's spam

**Comment by beltocas** [comment]
It was divided into 2 important processes:
1. Pre-processing
      Number of people: 1
2. Model and training
      Number of people: 3

**Comment by ZDev-19** [comment]
Created Pull Request for Issue . Date 07/09 Linked in issue description

**Comment by beltocas** [comment]
They occurred in other issues, based on the agreement meeting of 09/28
