### ISSUE TITLE
[FE] feat (Register): create register page

### ISSUE THREAD

**Issue by AnthonyRicse98** [unmsmfisi-socialapplication/social_app#208]
create register page according to figma 
https://www.figma.com/file/WyhCIiSidyM6aXsbxdu1rI/Dise%C3%B1o-UX%2FUI--App-Social?type=design&node-id=6-2&mode=design&t=Ut9ojp1E0KhlSfRm-0

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/73305764/1f2be1bf-c2fc-490e-8396-757a8cc3aeca)

Consider certain things 

- placeholders and titile in spanish
- do not put the google button
- do not put el remember me 

only build the body of the login according to the design, not do the logical part

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/73305764/82596f69-d863-4821-8abc-bfa9c7b3d6e9)

Use the existing atomic components as well as the organisms, guided by the construction of the login page

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/73305764/11d7dcee-1f02-49f3-9824-0634c4ba3edd)

For rendering it is necessary to create a page.tsx file in the register folder

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/73305764/db467000-8122-4443-957f-3ae6f8931781)

**Comment by joseph-robles** [comment]
A Pull Request #227 has been opened. Please review it.

**Comment by eds000n** [comment]
I think we can close this task

**Comment by joseph-robles** [comment]
Closing it right now. Thanks.
