### ISSUE TITLE
[DEVOPS] monitor stages

### ISSUE THREAD

**Issue by pieroHernandezC** [unmsmfisi-socialapplication/social_app#214]
integrate with monitoring tools and create dashboards for this. See [grafana](https://grafana.com/)

**Comment by serv10** [comment]
**About Grafana**

Grafana is a widely used open source platform for real-time data visualization and monitoring. Some of the advantages of using Grafana include:

1. **Data Source Flexibility**: Grafana can connect to a wide variety of data sources, including SQL databases, NoSQL, monitoring systems, cloud services, and more.

2. **Interactive Dashboards**: Grafana dashboards are highly interactive, allowing users to explore and drill down into data with ease. You can click on data points, apply filters, and adjust time ranges dynamically.

3. **Alerts and Notifications**: Grafana offers alerting capabilities that allow you to define thresholds and conditions to generate alerts when unwanted events occur.

4. **Scalability**: Grafana is scalable and suitable for small and large projects. You can deploy it on a single server or in a distributed cluster to handle intensive workloads.

5. **Integration with Monitoring Systems**: Grafana can integrate with monitoring systems such as Prometheus, InfluxDB and others, allowing you to consolidate and visualize monitoring data in one place.

6. **Open Source and Customization**: Grafana is open source, which means you can customize and extend its functionality according to your needs. Furthermore, it is free and free to use.

**Comment by pieroHernandezC** [comment]
Also The use of Google Cloud for application monitoring offers a number of benefits:

- [x] Monitoring tools: Google Cloud offers monitoring tools, such as Google Cloud Monitoring and Google Cloud Logging, that allow us to monitor both the frontend and backend in real time. These tools can help identify problems quickly and take action to resolve them.
- [x] Performance analysis: provides tools to analyze the performance of your application, allowing you to identify bottlenecks and optimize your code and resources for better performance.
- [x] Security: Google Cloud has robust security measures to protect your data and applications, which is essential for monitoring critical applications.
- [x] Managed services: Google Cloud offers managed services for databases, containers and other technologies, making it easy to manage system components without worrying about server administration.


![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/85851326/6df3e36f-77c0-45f5-9cf7-37e251dbeeb9)

**Comment by eds000n** [comment]
have you come to a conclusion about this?

**Comment by andresrdlc** [comment]
I have enabled monitoring services for the PostgreSQL database instance. In the case of the frontend and backend, the Cloud Run service has its own metrics section. This, added to the logging service that was also enabled, offers us a complete and integrated monitoring and observability solution, as well as customizable, for our entire application on Google Cloud Platform (GCP).

**Backend:**

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/113413391/8fb428b4-94f9-41df-a8e5-87e721c39f14)

**Frontend:**

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/113413391/068d8b4d-2605-43ed-bf4a-e414d6d116d7)

**PostgreSQL server:**

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/113413391/bbfd744b-012b-4142-955e-f09efb110466)

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/113413391/920bc149-3b38-43b4-9082-4723bd82cd72)

**Comment by eds000n** [comment]
@andresrdlc you have to do this programmatically (using terraform), think in the case that we wanna split the backend in microservices, each microservice will have its own DB and you cannot just manually enable the monitoring for each one of them

**Comment by andresrdlc** [comment]
For the deployment to production (main) we are planning to use Terraform, we are still learning this technology, since Terraform Cloud also exists and we were evaluating if we could use it. Personally I'm starting to explore infrastructure as code and I find it very interesting. Our current goal is to be able to enable all the services we use for the backend, frontend and database, etc., in this way using code.
