### ISSUE TITLE
[DEVOPS] decide how to automatically deploy the application

### ISSUE THREAD

**Issue by pieroHernandezC** [unmsmfisi-socialapplication/social_app#216]
on a deployment event, let's see how to deploy and where to deploy, the number of stages we will have
where:
- aws, google, linode, digital ocean, heroku (check free plans if any)

**Comment by eds000n** [comment]
how is this different to current deployments? I think we're missing a specific version release, the one which gets triggered when we move code from `develop` to `main`, which I consider a production environment. Deployments done when something gets merged into `develop` could be considered as `qa` or `testing`
