### ISSUE TITLE
[DATA] Post Classifier - Create script for post classification

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#259]

**Comment by 11LuisQuispe11** [comment]
In this issue what we will try to achieve is to **create** the .py file of our model, remember that our model is oriented to discover what type of topic is being discussed in the publication of our social network: this topic can be about some already predefined ones, such as: sport, politics, among others

**Comment by ZDev-19** [comment]
Issue closed due to  approved pull request
