### ISSUE TITLE
[DATA] Define processes for files creation and upload in shared platform (Testing)

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#261]

**Comment by Patrickpisana23** [comment]
### **implement function subir_archivo**

Author: @Patrickpisana23 
Creation Date: [05/10/2023]



### Description:


In this python script you use the 'Pydrive2' library to interact with google drive to perform operations such as create text or image file and upload file to your Google Drive account.

- **Function crear_archivo_texto:**

This feature creates a text file in Google Drive with a specified name, content, and destination folder.

-** Function subir_archivo:**

This feature uploads a local file to Google Drive, specifying the destination folder in Google Drive and the file name in Google Drive.


- **Unit Test test_subir_archivo:**

The unit test is test_subir_archivo defined using unittest. 
This test is responsible for testing the function subir_archivo. A test local file path (ruta_archivo) and test folder ID are defined in Google Drive (id_folder).
The subir_archivo function is then called with these test values.

**Comment by ZDev-19** [comment]
This issue had been completed and linked Pull Request was merged with no conflicts , clusing issue
