### ISSUE TITLE
[DEVOPS] deploy backend

### ISSUE THREAD

**Issue by andresrdlc** [unmsmfisi-socialapplication/social_app#273]

**Comment by andresrdlc** [comment]
**Development Environment:**
A continuous deployment is needed, which is why it will be deployed using GCP (Google Cloud Platform) - Cloud Run, this technology is Google Cloud's response to the implementation and execution of serverless containers, in this way there will be an auto-scaling environment for be able to measure the capacity needed in a future production environment.
A Dockerfile file will be defined, this will be used to create the image and run the container that will be deployed in Cloud Run, _**each "push" or merge in the Develop branch will activate the CD (Continuous Deployment) pipeline**_, the pipeline will execute the task of storing the Docker image in an Artifact Registry repository in GCP (social-app-backend-repo) and this image will be consumed by a Cloud Run service (social-app-backend-service).

URL api backend: [https://social-app-backend-service-7bg5siys2q-uc.a.run.app](url)

**Production environment:**
It will be deployed in the same way using Cloud Run, each time a release is completed and the Main branch is merged.
We will evaluate whether it will be necessary to deploy to a Compute Engine VM in GCP, depending on the needs of the project and taking into account the free tier and the $300 awarded by GCP.

**Comment by eds000n** [comment]
we could use Google Cloud Run (containers) instead of Compute Engine (VMs), if the whole team is fine with this then let's go on
