### ISSUE TITLE
[DEVOPS] standarize containers for different components

### ISSUE THREAD

**Issue by andresrdlc** [unmsmfisi-socialapplication/social_app#295]
Please containerize all the components so it's easy to test and run in a local environment using docker and docker-compose

**Comment by andresrdlc** [comment]
I will be in charge of defining and updating the Dockerfile and docker-compose for the **Backend** of the application.

**Comment by labrdev** [comment]
I would be in charge of creating and updating the Dockerfile for the Data ML application. But prior to this, it's needed to have implemented the Jupyter notebooks in actual Python code. Also, #383 for a centralized way of managing the dependencies and configs.
