### ISSUE TITLE
FE feat [ input] : create display password

### ISSUE THREAD

**Issue by AnthonyRicse98** [unmsmfisi-socialapplication/social_app#317]
feat input component 
use material iu 
material iu : https://mui.com/material-ui/react-text-field/ 

A prop will have to be created that allows a button to appear that allows the password to be displayed 
test it on the test page
![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/73305764/21625640-c42a-4d5f-9793-7209a5c8433c)

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/73305764/4fe5639f-dcef-4d2b-9e59-7e78d82c9fd8)

**Comment by eds000n** [comment]
This is done already, I think we can close this issue
