### ISSUE TITLE
[DATA] Improving sentiment analysis code with pyspark

### ISSUE THREAD

**Issue by beltocas** [unmsmfisi-socialapplication/social_app#330]
According to the meeting of 04/10
improve the sentiment analysis code with pyspark with testing approved by the author

**Comment by AdemirEstudiante** [comment]
Adding the function of searching the data frame with a URL
Author: @AdemirEstudiante
Creation Date: [06/10/2023]

Fulfilling the task assigned in https://github.com/unmsmfisi-socialapplication/social_app/issues/330, I proceed to code.

Description:
The option to use URL directly to load the data frame has been 
#378

**Comment by ZDev-19** [comment]
This issue was discussed in meeting documented at #409 , Pull request was closed
