### ISSUE TITLE
[DATA] Improve the post classification model

### ISSUE THREAD

**Issue by beltocas** [unmsmfisi-socialapplication/social_app#331]
Segun la reunion de del 04/10
mejorar del codigo de clasificacion de post  con el testing aprobado por el autor

**Comment by EGH2019** [comment]
There's few things to change , because there is only the test code at the moment

**Comment by EGH2019** [comment]
The file reading path variable was parameterized

**Comment by ZDev-19** [comment]
In previous discussion with @beltocas and @EGH2019 , this isssue is being closed due to further changes in model design according to new workflow at #411
