### ISSUE TITLE
[DEVOPS] deploy frontend

### ISSUE THREAD

**Issue by pieroHernandezC** [unmsmfisi-socialapplication/social_app#394]
Use a docker for frontend deployment in local and cloud server

**Comment by pieroHernandezC** [comment]
Follow the next steps for deploy the docker in local

First go to the frontend folder and run the following command to create the docker image:

``
cd ./frontend
``
``
docker build -t social-app:v1
``

Now we start the server using the previously created image, using the following command:

``
docker run -p 3000:3000 social-app:v1
``

**Comment by andresrdlc** [comment]
Once the Dockerfile is defined, I will add continuous deployment using Artifact Registry in GCP to store the images. It will then be deployed in Cloud Run using the last stored image.

**Comment by eds000n** [comment]
I think we can close this, frontend is automatically deployed now
