### ISSUE TITLE
[DATA] Proposed Data workflow

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#411]
### **Description**
The member @EGH2019 proposed a new workflow for DATA team , which was approved by voting and its official for team

**Comment by EGH2019** [comment]
According to the meeting we had on 10/10, this is a possible structure proposed using AWS services as a guide but it must be adapted according to the gpc services.
![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/54995563/977e12e4-a7ad-473c-9b06-118e57834183)
this diagram its a guide of the workflow proccess that we have.

**Comment by labrdev** [comment]
Possible future tasks needed for running the workflow.
- [ ]  Script for extracting and consolidating the data
- [ ]  Script for processing consolidated data and transforming it respecting each model
- [ ]  Script for training and saving in the cloud the Spam Model
- [ ]  Script for training and saving in the cloud the Post-Classification Model
- [ ]  Script for training and saving in the cloud the Sentiment Model
- [ ]  Deploy an endpoint for the consulting service and execution of trained models
- [ ] Prepare environment in GitHub Actions for running the scripts as pipelines.

**Comment by labrdev** [comment]
The deployment of the MLs endpoints is being discussed in #371

**Comment by ZDev-19** [comment]
### **Closing issue due to complete documentation**
