### ISSUE TITLE
[DATA] Parameterize model variables in spam detector

### ISSUE THREAD

**Issue by gustavo-guerreros1** [unmsmfisi-socialapplication/social_app#412]
The code has been configured to allow easy modification of the file URL, column names, feature parameters, and data splitting, as well as the time interval between model executions. This facilitates program adaptation to different datasets and requirements, providing flexibility and ease of maintenance. References: #412  , @gustavo-guerreros1

**Comment by gustavo-guerreros1** [comment]
**clean_text:** 
This function cleans the text from unwanted characters and performs tokenization and stopword removal, enabling effective data preparation for analysis. The function is parameterized as it uses a list of English stopwords and carries out cleaning operations based on regular expressions to adapt to different types of text.

**Comment by gustavo-guerreros1** [comment]
**### load_and_analyze_data**: 
This function loads and analyzes a file from a given URL, facilitating the integration of different datasets into the model without the need to modify the underlying code. The URL is parameterized and can be easily modified to load different datasets.

**Comment by gustavo-guerreros1** [comment]
**train_and_evaluate_model:** 
This function trains and evaluates the model using classification techniques such as Naive Bayes and Logistic Regression. The parameterized variables, such as the test size and the maximum number of features, allow flexible adjustment of the model to different datasets and evaluation requirements. The function also employs parameterized tokenization and text processing techniques to ensure consistency across different types of text data.

**Comment by gustavo-guerreros1** [comment]
**classify_comment:** 
This function classifies a comment as "spam" or "not spam" using Naive Bayes and Logistic Regression models. The use of classifiers and parameterized text cleaning function ensures robust adaptability of the model to various types of comments, enhancing its generalization capability in different contexts and applications.

**Comment by ZDev-19** [comment]
Closing issue due to accepted Pull Request
