### ISSUE TITLE
[DATA] GET BD connection

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#415]
### **Objective**
Make a successful connection with a Database for testing requirements , is not contemplated to use the official Backend Team BD

**Comment by baneuser** [comment]
**Connection to a database for our Data team**

- In this activity, you implement a connection to a SQL Server database in Azure Cloud from the Golang programming language
- The set of tables that will be used for this representative task is a temporary table called Person with columns ID, First Name and Last Name.

1. Task Objective

- The objective of this task is to connect to a database for the Data team.

2. Task Requirement

<html>
<body>


Requirement | Name | Definition
-- | -- | --
R_P01 | Firewall rules | Allow certain public Internet IP addresses to access the resource.
R_P02 | Golang | Version 1.21.3.


</body>
</html>

3. Table description

<html>
<body>


Table | Name | Description
-- | -- | --
R_T01 | Person | Temporary table for tests.


</body>
</html>

4. Pull request and commit

- All files required for deployment, such as the Go code for connecting to the database created in Azure Cloud and the message displayed in the program for successful execution, will be integrated into the repository using "Pull Request" via the "DATA_cnx_db" branch.

6. Results

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/69781563/ff2d910c-4987-4047-b44b-a887c0cccfe0)

**Comment by ZDev-19** [comment]
### **Confirmation and closing**

The member @baneuser confirms the PR and met the deadline. The PR was approved without problems , closing issue
