### ISSUE TITLE
[DATA] Get Social media data from API

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#416]
### **Objective**
Research all posible social Media API in order to test data collection

**Comment by ZDev-19** [comment]
### **Observation**

Pending Issue , deadline discussed on 27/10

**Comment by vladnn100** [comment]
**Get Social media data from API**

- In this activity, it's developer script uses the social media APIs Reddit and Instagram to connect with them and obtain their data.
- The documentation to be used for this task is reddit api documentation (https://www.reddit.com/dev/api/) and Instagram Graph API (https://developers.facebook.com/docs/instagram-api/).
-The data obtained comes directly from the database of the social networks Reddit and Instagram
