### ISSUE TITLE
[DATA] Provisional Azure instance and configuration alternative

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#500]

**Comment by baneuser** [comment]
**Previous considerations**
The objective of PR #489 is an important step to have an instance in a cloud database, the credentials for access are exclusive to our Data team for testing. Now, the next step is to comply with the database tools accepted by our team from the project planning stage, that is, the postgres database.

**Provisional Azure instance and configuration alternative**
- In this activity, a database server will be created using the cloud service called "Azure Database for PostgreSQL flexible servers", and perform connection testing with Data team member @AdemirEstudiante and the creation of base table objects for the purpose of the tests for Data's team.
- The set of tables that will be used for this representative task are the following relational tables: Post (posts), Users (users) and Comment (comments).

**Comment by baneuser** [comment]
1. Task Objective

- The objective of this task is to have a provisional instance in Azure for our Data team, so that we can carry out our tests in collaborative work with the different members.

2. Task Requirement

Requirement | Name | Definition
-- | -- | --
R_P01 | Azure Database for PostgreSQL flexible servers | Create the database server in this service in Azure Cloud
R_P02 | PostgreSQL Database Server v14.9 | Open source PostgreSQL packages and installers from EDB.
R_P03 | PgAdmin 4 v7.3. | Open Source administration and development platform for PostgreSQL
R_P04 | Credentials | Exclusive access for the Data team

3.

**Comment by baneuser** [comment]
3. Instalation and Configuration

- The cost of creating the instance has been as follows using exclusively the free tier in Azure Cloud (USD 16.09/month):

![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/69781563/cc921083-9cf1-497f-aa61-040fbcec4947)

- Once the cloud server is created, the tools mentioned in R_P02 and R_P03 are installed locally. In this stage, the connection is tested from the PC of another member of the Data team, @AdemirEstudiante:

![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/69781563/0fca9d71-14b8-4ace-823f-4bce9c7afeba)

- The connection is created:

![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/69781563/80ccce8c-363a-4e43-b765-278410c6b277)

![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/69781563/d60222df-3c51-46f0-810b-7d55dda5874c)

![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/69781563/87d3d8ff-5157-42eb-95ef-93880cefa9f7)

- The connection is successfully achieved

![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/69781563/18e6812d-a5e8-4c4e-a320-a8bc9ff248ce)

- To finish, try a select to the main tables

![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/69781563/a266e959-1745-46c5-a39b-289a21fb27f1)

**Comment by baneuser** [comment]
6. Pull request and commit

- All the files required for the connection, such as the Python code to connect to the database created in the Azure cloud and the message displayed in the program for successful execution, will be integrated into the repository using "Pull Request" to via the "DATA_dbpg" branch.

7. Results

![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/69781563/4d287087-4562-4ec0-9a26-29d6824e8f31)

**Comment by ZDev-19** [comment]
This issue PR is completed , discussion with assignee is pending for development comments and perspective about Azure

**Comment by eds000n** [comment]
set the infra as code: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_database
use env variables in the scripts to connec to the data source

**Comment by eds000n** [comment]
@aronlabr please have a look here as well
