### ISSUE TITLE
[DATA] Spam detection processes division

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#511]

**Comment by gustavo-guerreros1** [comment]
### Description
This task focuses on the organization and division of processes related to spam detection in a specific dataset. The creation of a folder and file structure is required to maintain a clear and well-organized workflow. The task involves segmenting the code into three main sections: execution, preprocessing, and training. The folder and file structure is designed to facilitate the understanding and maintenance of the project, with each component expected to perform specific functions related to spam detection.

**Comment by gustavo-guerreros1** [comment]
### **Justification**

Dividing the code into different files and folders is crucial for maintaining clarity and organization in the development of software projects. Organizing the code into separate logical sections makes it easier to identify and maintain each component, thereby improving teamwork collaboration and project scalability. Additionally, clear and detailed documentation provides essential information about the function of each component and its relationship with other parts of the project, making it easier for other developers to understand and use the code.

The specific folder and file structure is designed to clearly reflect the different processes involved in spam detection, from initial data manipulation to the training of machine learning models and the ongoing execution of the process. This allows for a clear separation of responsibilities and functions, which in turn facilitates error correction and system improvements in the future.

**Comment by gustavo-guerreros1** [comment]
**Project Structure**
The task involves creating the following folder and file structure:

**Main folder: **data****

Subfolders:

execution
preprocessing
training
Files in each subfolder:

In the execution folder: sp_lr_sklearn_main.py
In the preprocessing folder: sp_lr_sklearn_preprocessing.py
In the training folder: sp_lr_sklearn_training.py
The organization into folders and files allows for a structured and clear workflow for spam detection, facilitating the overall maintenance, understanding, and scalability of the project.
