### ISSUE TITLE
[QA] Branch creation

### ISSUE THREAD

**Issue by luzelenatt** [unmsmfisi-socialapplication/social_app#52]
Administrator access has been granted to @felixalfonsofernandez.

To do this, the creation of the 'develop' y 'qa_contracts' branch is requested. Please confirm if its creation has been completed.

**Comment by luzelenatt** [comment]
OK @felixalfonsofernandez the branches can be viewed on GitHub. In the "qa_contracts" branch, the contracts established in the following tasks will be uploaded in relation to it.

**Comment by eds000n** [comment]
I don't remember why we need this branch

**Comment by felixalfonsofernandez** [comment]
@eds000n in this case 'developer' was created to make a pre-production product of the project and 'qa_contracts' for QA guidance contracts.

**Comment by eds000n** [comment]
what's the point of the branch? we have a QA folder where we store contracts

**Comment by felixalfonsofernandez** [comment]
yes @eds000n, this issue was created before of the creation of QA folder.

**Comment by eds000n** [comment]
then let's close this issue as it isn't relevant anymore

**Comment by felixalfonsofernandez** [comment]
ok @eds000n i will close it right now
