### ISSUE TITLE
Configuring IaC to Azure instance

### ISSUE THREAD

**Issue by syntx8** [unmsmfisi-socialapplication/social_app#572]

**Comment by baneuser** [comment]
1. Problem Statement:

- This overarching issue addresses the implementation of Infrastructure as Code (IaC) for efficient management of Azure instances within our Data team's environment. It encompasses multiple facets crucial for seamless operation and collaboration.

3. Breakdown of Tasks and Resolved PRs:

- #814: Tasked with structuring the framework for Azure instance management, establishing the groundwork for subsequent configurations.

- #886: Focused on the IaC setup specifically tailored for resource groups, user groups, and user provisioning within the Azure environment.

- #982: Encompassed the assignment of roles and the creation of custom roles via IaC for precise access control and permissions management.

4. Completed Pull Requests:

- #876: Implemented conventions and best practices for Azure instance creation, ensuring uniformity and scalability.

- #888: Resolved the IaC configurations for GroupResources, user groups, and user provisioning, aligning with project requirements.

- #1026: Finalized role assignments and custom role creation through IaC, enabling granular control over permissions and access.

5. Impact:

- This comprehensive issue has significantly bolstered collaboration within the Data team by allowing parallel workstreams, fostering efficient resolution through branching, and laying the groundwork for a robust Azure instance management system via IaC.
