### ISSUE TITLE
[Data] weekly meeting 4/10

### ISSUE THREAD

**Issue by beltocas** [unmsmfisi-socialapplication/social_app#585]
Pending reu data:

* PR approval to order (Alonso)
* Approval of PR Jorge
* Raise observations of ticona in gregory's PR #500

Postclassification:

*The post classification model has not been renewed until now
(Mention those assigned as it will be their EC2)

* Model deployment

* Azure Discussion

* Management of model dependencies

* Backend contact

*QA contact

* Testing: Testing is missing / more PR and issues can come from here ()

**Comment by syntx8** [comment]
The title of the issue is corrected, where the date was wrong and was not related to the date of the comment.
