### ISSUE TITLE
[DATA] Bi_structuring for data visualization

### ISSUE THREAD

**Issue by beltocas** [unmsmfisi-socialapplication/social_app#601]
There will be 3 points to analyze, of which the extraction model, data transformation and data loading will have to be structured.

1. Data extraction.
2. Data transformation.
3. Data loading.

**Comment by beltocas** [comment]
1. Data extraction: 

A connection will be made directly to the database so that data can be inserted, which will have the following structure:



![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/45313496/bb412db3-73ab-4b60-b389-7df179dd7030)

**Comment by beltocas** [comment]
2. Data transformation.

It will work based on the consumption of a stored procedure in which it will take into account 3 steps:
- Delete today's data
- Validation of the user's ID that is correct, duplicates.
- Insertion of data into the final table.

**Comment by beltocas** [comment]
Folder Structure:
BI
- ddl
- store_procedures
- migration

**Comment by ekimike** [comment]
Have you considered, instead of manual deletion using jobs  from the RDBMS or cron jobs from the OS?, as the deletion could be resource and time consuming task, and blocking as being part of a pipeline

**Comment by baneuser** [comment]
Professor Miguel (@ekimike), to complement our automated deployment via Azure Data Factory, I wanted to let you know that we are currently in the process of documenting this flow in a Pull Request in our GitHub repository.

This detailed documentation will include information about how the automated process has been configured, the specific steps being performed in Azure Data Factory for data deletion, as well as any important considerations related to performance, execution frequency, and management. of errors.

**Comment by baneuser** [comment]
@ekimike. This topic was discussed, and the continuity of the aforementioned purpose is viable.
