### ISSUE TITLE
[DATA] create posts topic classifier

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#63]
based on the content of a post, we have to classify it in a bunch of topics. Decide how to trigger the processing

- Clustering

**Comment by ZDev-19** [comment]
This task was divided into two new issues:

- Data of post for preprocessing
- K - Means Model construction and testing via score

**Comment by beltocas** [comment]
They occurred in other issues, based on the agreement meeting of 28/09

**Comment by beltocas** [comment]
They occurred in other issues, based on the agreement meeting of 28/09
