### ISSUE TITLE
[DATA] bi_Dataframe migration to postgresql

### ISSUE THREAD

**Issue by beltocas** [unmsmfisi-socialapplication/social_app#682]
The following structure was defined to be able to migrate the data generated by prediction and classification models such as spam detection, post classification and sentiment analysis directly to a Postgresql table.

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/45313496/e6aa707e-c314-457e-971d-882f48cedd75)

This migration is based on the consumption of data, which is important for the data visualization subteam, they will consume directly from these sources that we will feed through a function in python.

**Comment by beltocas** [comment]
We will install the following library that allows us to make a connection with postgresql

pip install psycopg2-binary

**Comment by beltocas** [comment]
This library allows us to make 6 important points:

Connect to PostgreSQL: Allows Python programs to connect to a PostgreSQL database server, making it possible to execute database operations directly from Python.

Execution of SQL queries: Facilitates the execution of SQL commands (such as SELECT, INSERT, UPDATE, DELETE) from Python code, allowing users to read, modify, and manage data in the PostgreSQL database.

Transaction Management: Provides tools to control transactions, which is essential to maintain data integrity, especially in applications where multiple operations depend on each other.

Type Conversion: Automatically converts data between PostgreSQL types and Python types, simplifying the process of working with complex data such as dates, decimals, and arrays.

Security: Provides mechanisms for secure management of database credentials and connection handling, including support for SSL and robust authentication methods.

Efficiency: It is known for its efficiency and stability, making it suitable for use in production in systems that require high performance.

**Comment by beltocas** [comment]
The main difference between psycopg2 and psycopg2-binary is that the latter comes with the binary libraries already compiled, which makes installation easier as it does not require compiling the C components during installation, eliminating the need to have the corresponding development dependencies on the system where it is installed. However, developers often recommend psycopg2 over psycopg2-binary for production applications due to better compatibility and stability practices.

**Comment by ekimike** [comment]
I think it would be worth having a diagram or explanation about this complex pipeline because this diagram is so big picture. Remember that other team members wouldn't understand this process in detail.

**Comment by beltocas** [comment]
Close issue, because the new data base is Azure
