### ISSUE TITLE
[DATA] SparkNLP - Sentiment analysis

### ISSUE THREAD

**Issue by syntx8** [unmsmfisi-socialapplication/social_app#70]
**Sentiment Analysis with Pyspark**

- In this activity, I propose to implement a sentiment analysis powered by pyspark using four machine learning approaches: Logistic Regression, SVM, Naive Bayes, and Random Forest.
- The dataset to be used for this task is the annotated Tweets from "Sentiment140", which originated from a Stanford research project (http://help.sentiment140.com/for-students/).

### 1. Task Objective
- The objective of this task is to train and evaluate the four machine learning models (Logistic Regression, SVM, Naive Bayes and Random Forest) using previously processed data.

### 2. Task Requirement

| Requirement | Name | Definition |
| --- | --- | --- |
| R_P01 | Code commenting | Include comments in the source code to explain its functionality and make it easier to understand. |
| R_M02 | Model parameter selection | Select the appropriate parameters to set up the Logistic Regression, SVM, Naive Bayes, and Random Forest models. |
| R_M03 | Model evaluation | Perform performance tests on models using metrics such as accuracy, F1 score, and ROC curves. |

### 3. Model chosen and parameterization.

**Logistic Regression**
| Parameter | Value | Description |
| --- | --- | --- |
| maxIter | 15 | Controls the maximum number of iterations that the logistic regression algorithm takes. |
| elasticNetParam | 0.8 | Controls the mix between the regularizations in the logistic regression model. |
| regParam | 0.01 | Controls the strength of the regularization in the model. |

**SVM**
| Parameter | Value | Description |
| --- | --- | --- |
| maxIter | 5 | Controls the maximum number of iterations that the SVM algorithm takes. |
| regParam | 0.01 | Controls the strength of regularization in the SVM model. |

**Naive Bayes**
| Parameter | Value | Description |
| --- | --- | --- |
| smoothing | Varias iteraciones de 0.3 a 10 | Controls the Laplace smoothing applied to the Naive Bayes model. |

**Random Forest**
| Parameter | Value | Description |
| --- | --- | --- |
| standard | standard | none |

### 4. Pull request and commit
- All the files necessary for the implementation, such as the python code with the different models applying "Pyspark" and the data used, will be integrated into the repository by "Pull Request" through the "**DATA_add_sa_pyspark**" branch.

- The task has the following folder structure:
![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67533204/c50e7422-580f-47c4-995c-e93e160b7263)

### 5. Results
**Using Logistic Regression model with test data...**
![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67533204/b0f2a1e3-e790-4b88-9744-5359209353aa)

Logistic Regression Test Summary:
![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67533204/8c7f9dcb-a26a-4c6b-baed-3eeb65a5d2db)

- ROC (Receiver Operating Characteristic): **0.8017**
- F1 Score: **0.9430**
- Accuracy: **0.9416**

The Logistic Regression model performed reasonably well on the test data. It achieved an ROC score of 0.8017, indicating good discriminative power. The F1 score of 0.9430 and an accuracy of 0.9416 show that the model is effective at making accurate predictions.

**Using SVM model with test data...**
![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67533204/92daf3bb-a8fa-4eb4-9101-028fc281f124)

SVM Test Summary:
![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67533204/e75b2d55-dee7-42ba-bfa9-4a9ea8ed9917)

- ROC (Receiver Operating Characteristic): **0.8213**
- F1 Score: **0.9548**
- Accuracy: **0.9550**

The SVM model demonstrated strong performance on the test data. It achieved an ROC score of 0.8213, indicating good discriminative ability. The F1 score of 0.9548 and an accuracy of 0.9550 demonstrate the model's effectiveness in making accurate predictions.

**Using Naive Bayes model with test data...**
![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67533204/c372565a-a8c8-4ca8-98f6-54fb23245582)

Naive Bayes Test Summary:
![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67533204/a1af6843-3131-4c6d-bd79-d1f68ec4a6f5)

- ROC (Receiver Operating Characteristic): **0.8295**
- F1 Score: **0.8604**
- Accuracy: **0.8216**

The Naive Bayes model achieved reasonably good performance on the test data. It had an ROC score of 0.8295, indicating satisfactory discriminative power. The F1 score of 0.8604 and an accuracy of 0.8216 show that the model is effective in making predictions, although there is some room for improvement.

**Using Random Forest model with test data...**
![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67533204/78b2750d-9db0-4dea-8ac6-c5610eec606e)

Random Forest Test Summary:
![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67533204/2145e098-a88a-417f-b912-e295851ee725)

- ROC (Receiver Operating Characteristic): **0.5000**
- F1 Score: **0.8962**
- Accuracy: **0.9300**

The Random Forest model showed mixed performance on the test data. While it correctly predicted most instances of the negative class (8976 true negatives), it struggled to detect instances of the positive class, as evidenced by the 676 false negatives.

### 6. Discussion
- From the results obtained, the Logistic Regression and SVM models demonstrated strong performance, with high ROC scores and F1 scores. The Naive Bayes model showed reasonable performance but has some room for improvement. The Random Forest model, on the other hand, had difficulty distinguishing positive instances and yielded a lower ROC score.

**Comment by ZDev-19** [comment]
Closed due to linked pull request completed
