### ISSUE TITLE
[DATA] Pre-processing of post data posts topic classifier

### ISSUE THREAD

**Issue by baneuser** [unmsmfisi-socialapplication/social_app#72]
This preprocessing process may include tasks such as data cleaning, removal of redundant or irrelevant information, text normalization, tokenization (dividing the text into words or smaller units), and structuring the data in a way that is suitable for subsequent analysis. The aim is to prepare the data to be more useful and effective in future analyses or applications related to topic classification in social media posts.

**Comment by baneuser** [comment]
1. Objective of the issue/task:

Data Cleaning: Remove any redundant or irrelevant information in the posts to ensure that the data is clean and ready for analysis.
Text Normalization: Convert the text into a standardized format, such as converting all text to lowercase to avoid issues with case sensitivity.
Tokenization: Divide the text into words or smaller units (tokens) to facilitate further analysis.

The goal is to collect data through web scraping and preprocess it using the mentioned techniques.

2. Task requirements:

<html>
<body>


Requerimiento | Nombre | Definición
-- | -- | --
R_P01 | Comment code | The elaborated code must be commented for its better understanding
R_P02 | Application of the ETL process | Pandas, perform filtering operations, aggregation, cleansing, and data manipulation 
R_P03 | Data Cleaning | Pandas, library for manipulation and transformation of tabular data


</body>
</html>

**Comment by baneuser** [comment]
3. Conjuntos de Datos

    Pendiente

**Comment by ZDev-19** [comment]
Issue closed due to official Post classification selected , also new approach is being followed for the Pre-processing of data , future issues are expected
