### ISSUE TITLE
[DEVOPS] Setup CI

### ISSUE THREAD

**Issue by andresrdlc** [unmsmfisi-socialapplication/social_app#8]
Setup a Jenkins or GitHub Actions pipeline. Azure can be if it's for free

**Comment by andresrdlc** [comment]
A group meeting was held where various aspects of the first activity for the DevOps team were discussed.

Attached is the following Google Docs:
https://docs.google.com/document/d/1CdlA6FuJ6BZCregc5rEX4EQ7w1i-itC_--pMf4ZJU0g/edit?usp=sharing

**Comment by eds000n** [comment]
no docs

**Comment by eds000n** [comment]
ci will be hosted in github
