### ISSUE TITLE
[DATA] Azure roles management

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#815]

**Comment by EGH2019** [comment]
# Azure Data Team Roles and Permissions

As seen in the previous issue #814, the data team has been divided into three groups:

1. ml-team
2. bi-team
3. api-team

We have assigned default roles provided by the Azure platform for each team to ensure the necessary permissions. Below are the roles specified for each team:

## ml-team:
Azure Role | Purpose
-- | --
AzureML Compute Operator| Can access and perform CRUD operations on Machine Learning Services managed compute resources (including Notebook VMs).
Storage Blob Data Contributor | Allows for read, write and delete access to Azure Storage blob containers and data.
Reader | View all resources, but does not allow you to make any changes.

## bi-team:
Azure Role | Purpose
-- | --
Data Factory Contributor | Create and manage data factories, as well as child resources within them.
Storage Blob Data Contributor | Allows for read, write and delete access to Azure Storage blob containers and data.
SQL Server Contributor | Lets you manage SQL servers and databases, but not access to them, and not their security -related policies.

## api-team:
Azure Role | Purpose
-- | --
Data Factory Contributor | Create and manage data factories, as well as child resources within them.
API Management Contributor | Grants permissions to create, configure, and manage Azure API Management services.
Storage Blob Data Contributor | Allows for read, write and delete access to Azure Storage blob containers and data.
SQL Server Contributor | Lets you manage SQL servers and databases, but not access to them, and not their security -related policies.
AzureML Compute Operator| Can access and perform CRUD operations on Machine Learning Services managed compute resources (including Notebook VMs).
