### ISSUE TITLE
[DATA] Azure ML service for models

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#816]
# **Prepare the Model:**

Before deploying our model on Azure ML, it is crucial that the model is trained and saved in a compatible format. Let's make sure to complete the training and evaluation process using libraries such as Scikit-Learn, TensorFlow, or others, depending on our specific needs. We will save our model in a format accepted by Azure ML, such as a Scikit-Learn model file (e.g., .pkl) or a TensorFlow SavedModel (a directory with specific files).

**Comment by ZDev-19** [comment]
@syntx8 @orlando2400

**Comment by gustavo-guerreros1** [comment]
### **Subir el modelo a Azure:**

Para utilizar nuestro modelo en Azure ML, necesitamos almacenarlo en Azure, ya sea en Azure Blob Storage o en una carpeta específica en nuestro espacio de trabajo en Azure ML.
Subiremos nuestro modelo entrenado a Azure Blob Storage o a una carpeta específica en nuestro espacio de trabajo en Azure ML utilizando las herramientas proporcionadas por Azure o el SDK de Python.

**Comment by gustavo-guerreros1** [comment]
# **Definir un archivo de inferencia:**

Crearemos un script de inferencia que describa cómo realizar predicciones utilizando nuestro modelo, incluyendo funciones como init() para la inicialización y run(input_data) para realizar inferencias.
Desarrollaremos un script de inferencia en nuestro lenguaje de programación preferido (por ejemplo, Python) que incluya las funciones init() y run(input_data).

**Comment by gustavo-guerreros1** [comment]
# **Configurar un entorno de inferencia:**

Especificaremos las dependencias de nuestro modelo en un archivo de entorno, como myenv.yml para conda o requirements.txt para pip.
Definiremos las dependencias del entorno en un archivo, por ejemplo, myenv.yml, con las bibliotecas y versiones necesarias.

**Comment by gustavo-guerreros1** [comment]
### **Crear un entorno de inferencia:**

Configuraremos un entorno de inferencia que contenga las bibliotecas y dependencias necesarias para ejecutar nuestro script de inferencia.
Utilizaremos el archivo de entorno (myenv.yml) para crear un entorno de inferencia utilizando herramientas como conda o pip.

**Comment by gustavo-guerreros1** [comment]
# **Configurar y aprovisionar un servicio de inferencia:**

Utilizaremos Azure ML para configurar un servicio de inferencia, eligiendo entre Azure Container Instances (ACI) para despliegues sencillos o Azure Kubernetes Service (AKS) para escenarios más avanzados y de mayor escala.
Emplearemos el SDK de Azure ML para configurar un servicio de inferencia, utilizando, por ejemplo, AciWebservice para ACI o AksWebservice para AKS.

**Comment by gustavo-guerreros1** [comment]
# **Desplegar el modelo:**

Desplegaremos nuestro modelo en el servicio de inferencia configurado, generando un punto de conexión (endpoint) para realizar inferencias.
Desplegaremos nuestro modelo utilizando el SDK de Azure ML, cargando el modelo, el script de inferencia y el entorno de inferencia en el servicio que configuramos.

**Comment by gustavo-guerreros1** [comment]
### **Probar el servicio de inferencia:**

Probaremos el servicio de inferencia con datos de prueba para asegurarnos de que todo funcione correctamente.
Enviaremos datos de prueba al punto de conexión del servicio de inferencia y verificaremos las predicciones obtenidas.

**Comment by gustavo-guerreros1** [comment]
# **Gestionar y monitorizar el servicio de inferencia:**

Utilizaremos las herramientas proporcionadas por Azure ML para gestionar y monitorizar el rendimiento del servicio de inferencia, ajustando la escala, realizando actualizaciones del modelo y más.
Utilizaremos el portal de Azure o el SDK de Azure ML para gestionar y monitorizar el servicio de inferencia, realizando ajustes en la configuración, actualizando el modelo y evaluando el rendimiento.

**Comment by syntx8** [comment]
# Configure and provision an inference service
We will use Azure ML to configure an inference service, choosing between **Azure Container Instances (ACI)** for simple deployments or **Azure Kubernetes Service (AKS)** for more advanced and larger scale scenarios.
We will employ the **Azure ML SDK** to configure an inference service, using, for example, AciWebservice for ACI or AksWebservice for AKS.

**Comment by syntx8** [comment]
# Deploy the model
- We will deploy our model to the configured inference service, generating an endpoint to perform inferences.
- We will deploy our model using the **Azure ML SDK**, loading the model, the inference script and the inference environment in the service we configured.

**Comment by orlando2400** [comment]
# Test the inference service
- We will test the inference service with test data to make sure everything is working correctly.
- We will send test data to the connection point of the inference service and verify the predictions obtained.

**Comment by orlando2400** [comment]
# Manage and monitor the inference service
- We will use the tools provided by Azure ML to manage and monitor the performance of the inference service, adjusting scaling, performing model updates and more.
- We will use the Azure portal or the Azure ML SDK to manage and monitor the inference service, making configuration adjustments, updating the model, and evaluating performance.

**Comment by syntx8** [comment]
# Storage of predictions in Azure Storage for the DATA_BI team. [SA]

## Description.

In the collaborative context of the DATA_BI team, a strategic solution has been implemented to improve the access and availability of predictions generated by the **Sentiment Analysis model [SA]**. This document describes the integration of prediction storage into Azure Storage to facilitate efficiency and speed in the team's work.

## Objective.

The main objective of this integration is to provide an efficient method for storing and accessing predictions from the sentiment analysis model. By using Azure Storage, we seek to ensure fast and reliable access to the information needed for the DATA_BI team's data analysis tasks.

## Storage Platform: Azure Storage

### Reasons for the Choice

The choice of Azure Storage is based on the following considerations:

- **Security and Trust**: Azure Storage offers a secure and reliable storage solution for critical data.
  
- **Scalability**: The platform is highly scalable, ensuring that the team can manage future data growth efficiently.

- **Integration with Existing Tools**: Azure Storage easily integrates with other tools used by the DATA_BI team, facilitating the transfer and sharing of data within the Azure ecosystem.

## Integration Process

### Prediction Storage

Predictions generated by the sentiment analysis model are stored directly in Azure Storage. This process is performed automatically as part of the standard model output.

### Access to Predictions

Access to stored predictions is provided by direct queries to Azure Storage from the team's data analysis tools. Azure SDK libraries or Azure-provided user interfaces can be used to access stored data.

## Conclusions

The successful integration of Azure Storage for prediction storage provides the DATA_BI team with an efficient and reliable environment to manage the outputs of the sentiment analysis model. This contributes to the optimization of data analysis processes and improves collaboration within the team.
