### ISSUE TITLE
[DATA] Pre-processing data comments Spam detection

### ISSUE THREAD

**Issue by orlando2400** [unmsmfisi-socialapplication/social_app#84]
The main objective of this task is to preprocess the data, in this case the youtube api was used to extract comments from a particular video about Peruvian politics, the steps to be used include normalization and noise removal in the data by converting to lowercase only, removal of links, among other points. Finally the data will be exported in a csv file to be used in the Spam detection model.

**Comment by orlando2400** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-d75ef82c-7fff-6321-9dd0-c2ba5d6c8b26">Task requirements:<div dir="ltr" style="margin-left:0pt;" align="center">

<br>

Requirement | Name | Definition
-- | -- | --
R_P01 | Comment code | The realized code was commented in necessary parts.
R_P02 | Application of the ETL process | A logic will be applied to extract the data from the youtube api, then the data will be transformed and loaded to a .csv file.
R_P03 | Data Cleaning | Use of text preprocessing techniques in a social app.

</div></b>
</body>
</html>

**Comment by ZDev-19** [comment]
Closed issue , changes are merged in the respective Pull request.
