### ISSUE TITLE
[DATA] Nltk VADER - Sentiment analysis

### ISSUE THREAD

**Issue by beltocas** [unmsmfisi-socialapplication/social_app#90]

**Comment by beltocas** [comment]
Vader means: Valence Aware Dictionary and sEntiment Reasoner

This library is based on rules and a powerful lexicon to perform it's analysis and determine whether a new item is positive, negative or neutral.

The values that vader returns:

| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
| Row 1    | Cell 2   | Cell 3   |
| Row 2    | Cell 5   | Cell 6   |
| Row 3    | Cell 8   | Cell 9   |

**Comment by beltocas** [comment]
How install Vader?

1. type "pip install vadersentiment" in your spyder compiler or in cmd

**Comment by ZDev-19** [comment]
Functionatily not contemplated due to time limits , closed according to meeting 28/09
