### ISSUE TITLE
[DATA] Develop tables for model results

### ISSUE THREAD

**Issue by ZDev-19** [unmsmfisi-socialapplication/social_app#974]
### **Description**

Previous issue #910 develop an azure SQL DB connection , this was for API development , as discussed with @beltocas we need to load all model (post_classification , sentiment_analysis and spam detection) in official tables in DB instance in Azure. This is to reduce the complexity of API process that will extract data from DB not from Azure storage

**Comment by ZDev-19** [comment]
### **Process diagram**

In order to understand the process activity , with @beltocas and @vladnn100 we developed a diagram about all API process. I attach the Data load to database phase:

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67244623/6881903f-5dcb-426e-bdce-8372703893da)

Basically , all model results (predictions) are stored in Azure service in csv format, all of them are called to a FUNCTION script in order to load data in their respective tables:

- Master_post
- Master_sentiment
- Master_spam

All via connection with Azure DB , previously developed in #910

**Comment by ZDev-19** [comment]
### **About testing development**

According to @syntx8 , all model assignees @gustavo-guerreros1 and @orlando2400 are still in progres to load all results in the storage service , so in order to just prove the implementation the development is made just with @syntx8 dataset , in pending issue the process must be completed to extract from Azure storage service

**Comment by gustavo-guerreros1** [comment]
I hope you're doing well. I wanted to inform you that we have completed the loading of the data and the model into Azure Storage within the container named 'spmodelcontainer' as part of the development process. Now, both elements are available and ready for use.

If you need to access them or if there's anything else I can assist with, please feel free to let me know.

Thank you for your collaboration! @ZDev-19 

![image](https://github.com/unmsmfisi-socialapplication/social_app/assets/75128349/e4302c8a-8700-4bc3-b735-9d3b5c9bba98)

**Comment by ZDev-19** [comment]
### **Updates about development**

Great @gustavo-guerreros1 , i talked with @syntx8 about the results storage , it appears you completed the integration of service. However , for this issue its merely a logic implementation with data of @syntx8 , but the official integration is going to be in another "Refactoring issue".

Just to inform you , these were my considerations:

### SQL Alchemy
SQL alchemy is a library to give developers all methods in order to manage SQL  , the file conexion_sql.py was changed and added a method to use it:

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67244623/5ec349ec-2f11-42cd-a166-28bd1f9c0a01)

With this connextion SQLAlchemy engine is ready to use and load dataframes directly to DB

**Comment by ZDev-19** [comment]
### **Testing results**

With sentiment_analysis model results provided by @syntx8 , the test of upload logic was made . It was simple , try to upload all data in dataframe format to DB in azure , with 10 batches at minimum:

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67244623/0132e42d-80c0-4e9c-a034-1793b881560b)

First batch was uploaded at 7:50 p.m then last batch number 19 wat at 8:20 pm , the test was about 30m with a total to 19000 instances uoloaded succesfully in SQL DB in Azure

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67244623/c89282b8-0d6b-41d5-8547-8c03bc0d9a90)

The upload in Azure Portal:

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/67244623/48804c8f-6876-4fbc-a029-cc9a223c9b27)
