### ISSUE TITLE
[UX/UI] Corporate Image: part 1

### ISSUE THREAD

**Issue by WilkerAtalaya** [unmsmfisi-socialapplication/social_app#98]
Creation of the first part of the corporate image of the application:
-Essence of identity
-Core items
-Identity phrases

**Comment by WilkerAtalaya** [comment]
**_1. Essence of identity_**
   1.1. Logo
   1.2. Corporate colors
   1.3. fonts
   1.4. Business area

**_2. Basic elements of identity_**
   2.1. Logo
   2.2. Corporate colors
   2.3. fonts
   2.4. Business area

**_3. Identity phrases_**
   3.1. slogan
   3.2. brand voice

**Comment by WilkerAtalaya** [comment]
https://www.figma.com/file/vbTZ1U6N7npeCmIfHOH4q1/Transparent?type=design&node-id=0%3A1&mode=design&t=ytty8a3K38T8XXhy-1

**Comment by eds000n** [comment]
@unmsmfisi-socialapplication/ux-ui please have  a review here

**Comment by WilkerAtalaya** [comment]
This design alternative did not proceed
